version: '3.11'
services:
  streamlit:
    build: docker/streamlit
    image: tgaufa/stock_pred_streamlit_img
    container_name: stock_pred_streamlit_cont
    depends_on:
      - api
    ports:
      - 8501:8501
    volumes:
      - ./:/home/
  api: 
    build: docker/api
    image: tgaufa/stock_pred_fastapi_img
    container_name: stock_pred_fastapi_cont
    ports:
      - 8080:8080
    volumes:
      - ./:/home/
